name: DwarfCraft
description: A skills and progression plugin for character development in RPG worlds.
author: Jessy1237
main: com.Jessy1237.DwarfCraft.DwarfCraft
version: 3.1.4
depend: [Vault, Citizens]
softdepend: [LogBlock]
commands: 
   dcreload: 
      description: Reloads the DwarfCraft plugin.
      usage: |
           /dcreload
      aliases: []
   dcdebug: 
      description: Sets the debug message threshold in console, from -10(everthing) to +10(critical only).
      usage: |
           /dcdebug [debug level]
           Example: /dcdebug 2 - sets the console debug printing threshold to 2
      aliases: []
   dcinfo: 
      description: Displays general information about the DwarfCraft plugin.
      usage: /dcinfo Displays general information about the DwarfCraft plugin.
      aliases: [dchelp]
   dcrules: 
      description: Displays server rules defined in the DwarfCraft messages config file.
      usage: /rules Displays server rules defined in the DwarfCraft messages config file.
      aliases: []
   tutorial: 
      description: Displays a series of guide messages to instruct in the basics of DwarfCraft
      usage: |
             Displays a series of guide messages to instruct in the basics of DwarfCraft
             /tutorial <page number> 
             Example: /tutorial 2 - Prints the second tutorial section
      aliases: []
   dccommands: 
      description: Displays all DwarfCraft commands.
      usage: /dccommands Displays all DwarfCraft commands.
      aliases: [commands, commandslist] 
   skillsheet: 
      description: Displays a list of skills and levels for a Dwarf.
      usage: |
             Displays a list of skills and levels for a Dwarf.
             /skillsheet <full/-f)> <Player Name or blank>
             Example: /skillsheet smartaleq - Prints smartaleq's skillsheet
             Example: /ss -f - Prints your complete skillsheet with level 0 Skills
      aliases: [skills, ss]
   skillinfo: 
      description: Displays a description of a dwarf's skill and training costs
      usage: |
             Displays a description of a dwarf's skill and training costs
             /skillinfo <player name> [Skill ID or Skill Name]
             Example: /skillinfo 11 - Prints details about Excavation skill
             Example: /skillinfo Dirt_Digging - Prints details about Dirt Digging skill
             Example: /skillinfo smartaleq 3 - Prints details about Smartaleq's Axe use skill
      aliases: [skill, si]
   effectinfo: 
      description: 
      usage: |       
             Displays a description of a dwarf's effect information
             /effectinfo <player name> [EffectID]
             Example: /effectinfo smartaleq 131 - Prints details about Smartaleq's effect 131
      aliases: [ei]
   race: 
      description: Checks a players race information, or changes it.
      usage: |
             /race <Race name> <confirm>
             Example: /race - Displays the player's current race information.
             Example: /race elf - Displays information about the elf race.
             Example: /race elf confirm - Changes the player's race to elf and resets their skills.
             Admin: /race <Player> <Racename> <confirm> - Alters another player's race, use confirm.
      aliases: []
   setskill: 
      description: Admin command to change a players skill level manually.
      usage: |
             /setskill <player name> [Skill ID or Skill Name or All] [new skill level]
   creategreeter: 
      description: 
      usage: 
   createtrainer: 
      description: Creates a new trainer where you are standing.
      usage: |
             /createtrainer <ID> <DisplayName> <Skill ID or Skill Name> <Max Skill Level> <Min Skill Level>
      aliases: [ct]
   listtrainers: 
      description: Displays a list of trainers and greeters on the server.
      usage: |
             /listtrainers [PageNumber]
      aliases: [listtrainer, lt]
   races:
      description:
      usage:
   dmem: 
      description: Displays a list of what type, and how many entites are loaded on the server.
      usage: |
             /dmem
