name: ${project.name}
description: A skills and progression plugin for character development in RPG worlds.
author: Jessy1237
main: com.Jessy1237.DwarfCraft.DwarfCraft
version: ${project.version}
api-version: 1.13
depend: [Vault, Citizens]
softdepend: [LogBlock, PlaceholderAPI]
commands: 
   dwarfcraft:
      description: The base command for DwarfCraft
      usage: |
           /dwarfcraft
      aliases: [dc]
