name: DwarfCraft
description: A skills and progression plugin for character development in RPG worlds.
author: Jessy1237
main: com.Jessy1237.DwarfCraft.DwarfCraft
version: 4.0
depend: [Vault, Citizens]
softdepend: [LogBlock]
commands: 
   DwarfCraft: 
      description: The base command for all DwarfCraft commands. The old commands are now args to this command
      usage: |
           /DwarfCraft
      aliases: [dc]
